#!/bin/sh

set -e
LOGO_URL=$1

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

. /root/omv-theme/app/functions/ui-js-functions.sh; set_header_logo $LOGO_URL

exit 0