#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

case "$1" in
    remove)
    ;;

    purge)
        omv_config_delete "/config/services/theme"

        # uninstall omv-theme
          echo "Removing omv-theme folder and executable"
          rm -rf /root/omv-theme
          rm -rf /usr/bin/omv-theme
    ;;

    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;

    *)
        echo "postrm called with unknown argument '$1'" >&2
        exit 1
    ;;
esac

exit 0
