#!/bin/sh


set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

case "$1" in
    configure)
        # Activate package triggers. These triggers are only set during the
        # package installation.
        dpkg-trigger update-fixperms
        dpkg-trigger update-locale

        # Initialize and migrate configuration database.
        echo "Updating configuration database ..."
        omv-confdbadm create "conf.service.theme"
        if [ -n "$2" ]; then
            omv-confdbadm migrate "conf.service.theme" "${2}"
        fi

        echo "Check if previous omv-theme folder exists and delete them"
        rm -rf /root/omv-theme
        rm -rf /usr/bin/omv-theme

        echo "Creating omv-theme folder"
        cd /root/
        mkdir omv-theme
        cd omv-theme/

        echo "Pulling omv-theme from git repo..."
        #wget --no-check-certificate https://github.com/virgil-av/omv-theme/archive/master.tar.gz
        wget --no-check-certificate https://github.com/virgil-av/omv-theme/archive/develop.tar.gz

        echo "extracting omv-theme to /root/omv-theme"

        #tar -zxvf master.tar.gz
        #mv omv-theme-master/* ./
        #rm -rf master.tar.gz omv-theme-master/

        tar -zxf develop.tar.gz
        mv omv-theme-develop/* ./
        rm -rf master.tar.gz omv-theme-develop/

        echo "Creating executable omv-theme"
        chmod u+x install-for-ui.sh
        ./install-for-ui.sh

        echo "## omv-theme tool has finished to install ##"
        echo "Starting to update ui plugin files with latest from repo"

        echo "Check if previous ui plugin folder exists and delete it"
        rm -rf /root/omv-plugin

        echo "Creating omv-plugin folder"
        cd /root/
        mkdir omv-plugin
        cd omv-plugin/

        echo "Pulling omv ui plugin from git repo..."
        wget --no-check-certificate https://github.com/virgil-av/openmediavault-theme/archive/master.tar.gz

        echo "extracting ui plugin to /root/omv-plugin"
        tar -zxvf master.tar.gz
        mv openmediavault-theme-master/* ./
        rm -rf master.tar.gz openmediavault-theme-master/

        echo "copying files to folders"
        cp -au usr/share/openmediavault/* /usr/share/openmediavault
        cp -au var/www/openmediavault/* /var/www/openmediavault

        echo "Clean cache and restart omv rpc service"

        . /usr/share/openmediavault/scripts/helper-functions && omv_purge_internal_cache
        service openmediavault-engined restart

    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument '$1'" >&2
        exit 1
    ;;
esac

exit 0




